# Check this guide for more information about publishing to ghcr.io with GitHub Actions:
# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio

# Build the container image and push it to the registry
name: build-video

on:
  push:
    paths:
      - video.Containerfile

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: toolbx-video

jobs:
  build-video:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup and login to Quay
        uses: ./.github/workflows/container-reused-steps
        with:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
  
      - name: Login to Quay Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Container meta:${{ github.ref_name }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }},quay.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ github.ref_name }}
            latest

      - name: Install latest buildah
        run: |
          sudo apt-get update
          sudo apt-get -y install buildah
          buildah version

      - name: Buildah Action
        uses: redhat-actions/buildah-build@v2
        with:
          context: .
          containerfiles: |
            ./video.Containerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.ref_name }}
            RELEASE=${{ github.run_number }}
          platforms: linux/amd64
          oci: true
          extra-args: |
            --cache-from=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            --cache-to=ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}
            --layers=true

      - name: Build and push toolbx
        uses: redhat-actions/push-to-registry@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
