# Check this guide for more information about publishing to ghcr.io with GitHub Actions:
# https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions#upgrading-a-workflow-that-accesses-ghcrio

# Build the container image and push it to the registry
name: build-fedora-toolbox-41

on:
  push:
    paths:
      - fedora-toolbox-41.Containerfile

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the permissions granted to the GITHUB_TOKEN for the actions in this job.
permissions:
  contents: read
  packages: write

jobs:
  build-fedora-toolbox-41:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup and login to Quay
        uses: ./.github/workflows/container-reused-steps
        with:
          QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
          QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

      - name: Container meta:${{ github.ref_name }}
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/fedora-toolbox-41,quay.io/${{ github.repository_owner }}/fedora-toolbox-41
          tags: |
            ${{ github.ref_name }}
            latest

      - name: Build and push fedora-toolbox-41
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./fedora-toolbox-41.Containerfile
          push: true
          target: final
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ github.ref_name }}
            RELEASE=${{ github.run_number }}
          platforms: linux/amd64
          # Cache to registry instead of gha to avoid the capacity limit.
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/fedora-toolbox-41:cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/fedora-toolbox-41:cache,mode=max
          sbom: true
          provenance: true
